### ISSUE TITLE
No Role add of Verified

### ISSUE THREAD

**Issue by Strohgelaender** [GHCDiscord/ManagementBot#7]

**Comment by TotenKnopf** [comment]
Ist ein Problem mit der automatisch durch die Integration erstellen Rolle im Discord, kein Problem mit der Programmierung. 
bin dran.

**Comment by TotenKnopf** [comment]
habe einen neuen auth-link für die bot-app erstellt, um die Berechtigungen festzulegen.
Da der Bot in den Rollen +verified und +everyone ist, fehlt nur die Berechtigung zur Rollenverwaltung.
Hinweis: Es können noch Fehler auftreten, wenn der Bot Rollen von Teammitgliedern setzen soll. Dies kann er nicht, da er in der Rollenhirarchie zu weit unten sitzt.

BOT APP ID:
308509120645038091

DOK Permissions:
https://discordapp.com/developers/docs/topics/permissions#bitwise-permission-flags
"MANAGE_ROLES *	0x10000000	Allows management and editing of roles"

AUTH Link: (no permissions)
https://discordapp.com/api/oauth2/authorize?client_id=_____YOUR_ID_____&scope=bot&permissions=0

FIX: AUT Link: (manage roles permission)
https://discordapp.com/api/oauth2/authorize?client_id=_____YOUR_ID_____&scope=bot&permissions=0x10000000
